# Generated by Django 5.0.2 on 2024-02-23 14:06

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=90, scale=None, size=[41, 41], upload_to='site_info', verbose_name='لوگو')),
                ('title', models.CharField(max_length=40, verbose_name='عنوان')),
                ('short_description', models.CharField(max_length=250, verbose_name='توضیحات کوتاه')),
                ('main_description', models.CharField(max_length=1000, verbose_name='توضیحات اصلی')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('address', models.CharField(max_length=250, verbose_name='آدرس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیرفعال')),
                ('about_us_picture', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[451, 271], upload_to='about_us', verbose_name='تصویر درباره ما')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[185, 115], upload_to='team_member', verbose_name='تصویر')),
                ('fullname', models.CharField(max_length=35, verbose_name='نام و نام خانوادگی')),
                ('job', models.CharField(max_length=35, verbose_name='شغل')),
                ('description', models.CharField(max_length=250, verbose_name='توضیحات')),
                ('site_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='IndexApp.siteinfo')),
            ],
        ),
    ]
