# Generated by Django 5.0.2 on 2024-03-09 11:35

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndexApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='main_picture',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[831, 353], upload_to='main_picture', verbose_name='تصویر اصلی'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='side_picture',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[261, 106], upload_to='side_picture', verbose_name='تصویر کناری'),
        ),
    ]
