# Generated by Django 5.0.2 on 2024-03-09 17:54

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndexApp', '0003_remove_siteinfo_main_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpictures',
            name='picture',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[966, 353], upload_to='main_picture', verbose_name='تصویر اصلی'),
        ),
    ]
