# Generated by Django 5.0.2 on 2024-03-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndexApp', '0004_alter_mainpictures_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name': 'اطلاعات سایت', 'verbose_name_plural': 'اطلاعات سایت'},
        ),
    ]
