# Generated by Django 5.0.2 on 2024-02-24 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0002_alter_productrate_rate_alter_product_average_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rate',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='میانگین امتیازات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='products', to='ProductsApp.category', verbose_name='دسته بندی'),
        ),
    ]
