# Generated by Django 5.0.2 on 2024-02-24 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0004_alter_product_average_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rate',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='میانگین امتیازات'),
        ),
    ]
