# Generated by Django 5.0.2 on 2024-02-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0006_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت نهایی'),
        ),
    ]
