# Generated by Django 5.0.2 on 2024-02-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0007_alter_product_final_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorOfProduct',
            new_name='ProductColor',
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rate',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='میانگین امتیازات'),
        ),
    ]
