# Generated by Django 5.0.2 on 2024-02-24 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0008_rename_colorofproduct_productcolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ProductsApp.productcomment'),
        ),
    ]
