# Generated by Django 5.0.2 on 2024-02-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0013_alter_productimage_options_product_visited_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='visited_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='بازدید'),
        ),
    ]
