# Generated by Django 5.0.2 on 2024-02-27 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0014_alter_product_visited_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='visited_ip',
        ),
        migrations.CreateModel(
            name='ProductVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='آی پی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_visited', to='ProductsApp.product', verbose_name='محصول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_visited', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
