# Generated by Django 5.0.2 on 2024-02-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0015_remove_product_visited_ip_productvisited'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فروش'),
        ),
    ]
