# Generated by Django 5.0.2 on 2024-02-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0017_category_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url_title',
            field=models.SlugField(blank=True, default='automatic-set', verbose_name='عنوان در url'),
        ),
    ]
