# Generated by Django 5.0.2 on 2024-03-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0019_product_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvisited',
            options={'verbose_name': 'بازدید محصول', 'verbose_name_plural': 'بازدید محصولات'},
        ),
    ]
