# Generated by Django 5.0.2 on 2024-03-20 13:08

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0020_alter_productvisited_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='webp', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='product_images/', verbose_name='تصویر'),
        ),
    ]
