# Generated by Django 5.0.3 on 2024-03-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0021_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvisited',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='آی پی'),
        ),
    ]
