# Generated by Django 5.0.2 on 2024-03-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_user_card_number_user_date_of_birth_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر پروفایل'),
        ),
    ]
