# Generated by Django 5.0.2 on 2024-03-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_city_slug_province_slug_alter_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
