# Generated by Django 5.0.2 on 2024-03-08 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductsApp', '0019_product_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_random_number', models.CharField(max_length=10, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[(1, 'در انتظار پرداخت'), (2, ' پرداخت شده'), (3, ' ارسال شده'), (4, ' تکمیل شده'), (5, 'لغو شده')], default='1', max_length=10, verbose_name='وضعیت')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='مبلغ')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id', models.PositiveIntegerField(verbose_name='id رنگ')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('final_price', models.PositiveIntegerField(verbose_name='قیمت کل')),
                ('color', models.CharField(max_length=10, verbose_name='رنگ')),
                ('color_stock', models.IntegerField(verbose_name='موجودی رنگ')),
                ('weight', models.IntegerField(verbose_name='وزن')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CartApp.cart', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductsApp.product', verbose_name='محصول')),
            ],
        ),
    ]
