# Generated by Django 5.0.2 on 2024-03-08 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_random_number', models.CharField(blank=True, max_length=10, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('1', 'در انتظار پرداخت'), ('2', ' پرداخت شده'), ('3', ' ارسال شده'), ('4', ' تکمیل شده'), ('5', 'لغو شده')], default='1', max_length=10, verbose_name='وضعیت')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='مبلغ')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CartApp.cartmodel', verbose_name='سفارش'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
