# Generated by Django 5.0.2 on 2024-03-09 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0002_cartmodel_alter_cartitem_cart_delete_cart'),
        ('UserApp', '0009_alter_address_address_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserApp.address', verbose_name='آدرس'),
            preserve_default=False,
        ),
    ]
