# Generated by Django 5.0.2 on 2024-03-13 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0004_alter_cartmodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ سفارش'),
            preserve_default=False,
        ),
    ]
