# Generated by Django 5.0.2 on 2024-03-14 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0007_rename_total_price_cartmodel_final_price'),
        ('UserApp', '0010_city_slug_province_slug_alter_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.address', verbose_name='آدرس'),
        ),
    ]
